version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-backend-app
    ports:
      - "4000:4000"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - DB_HOST=mysqldb # Donot change mysqldb
      - DB_PORT=3306
      - DB_NAME=dummyDB
      - DB_USERNAME=root
      - DB_PASSWORD=dummy
    volumes:
      - ./:/usr/src/app
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - nodejs-mysql-network

  mysqldb:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=smart_data
      - MYSQL_ROOT_PASSWORD=dummy
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nodejs-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" # Expose phpMyAdmin on port 8080
    environment:
      - PMA_HOST=mysqldb # The hostname of the MySQL container
      - PMA_USER=dummy
      - PMA_PASSWORD=dummy
    depends_on:
      - mysqldb
    networks:
      - nodejs-mysql-network

volumes:
  mysql-data:

networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network
